site_name: StratOS-LiySTD 文档
  
theme:
  icon:
    logo: icos/logo256x.ico
  logo: icos/logo32x.png
  favicon: icos/logo16x.png
  name: material
  language: zh
  features:
    - content.code.copy
    - palette.toggle
    - navigation.instant
    - navigation.expand
    - toc.integrate
    - content.tabs.link

  # custom_dir: overrides
  # static_templates:
  #   - main.html

  palette:

    # Toggle light mode
    - media: "dark"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换到深色模式

    # Toggle dark mode
    - media: "light"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      pygments_style: material
      linenums_style: table
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.blocks.tab:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/theme-loader.js
  - js/sw.js

nav:
  - 欢迎来到LiySTD: index.md
  - StratOS-LiySTD 介绍: 
    - LiySTD 是做什么的: what.md
    - 项目结构: structure.md
  - 快速上手: 
    - 对于桌面环境: start/forDesktop.md
    - 对于嵌入式环境: build.md
  - API参考：快速浏览: 
    - STD数据类型: 
      - LinearListVitual: API/STD/LinearListVitual.md
      - ArrayListVirtual: API/STD/ArrayListVirtual.md
      - SinglyListVirtual: API/STD/SinglyListVirtual.md
      - SinglyCircularListVirtual: API/STD/SinglyCircularListVirtual.md
      - DoublyCircularListVirtual: API/STD/DoublyCircularListVirtual.md

      - LinearList: API/STD/LinearList.md
      - Array: API/STD/Array.md
      - SinglyList: API/STD/SinglyList.md
      - SinglyCircularList: API/STD/SinglyCircularList.md
      - DoublyCircularList: API/STD/DoublyCircularList.md


      - StackVirtual: API/STD/StackVirtual.md
      - QueueVirtual: API/STD/QueueVirtual.md
      - StackLinkVirtual: API/STD/StackLinkVirtual.md

      - Queue: API/STD/Queue.md
      - Stack: API/STD/Stack.md
      - StackLink: API/STD/StackLink.md

      - DictVirtual: API/STD/DictVirtual.md
      - DictArrayVirtual: API/STD/DictArrayVirtual.md
      - DictLinkVirtual: API/STD/DictLinkVirtual.md
      - SkipListVirtual: API/STD/SkipListVirtual.md
      - DictHashVirtual: API/STD/DictHashVirtual.md

      - Dict: API/STD/Dict.md
      - DictArray: API/STD/DictArray.md
      - DictLink: API/STD/DictLink.md
      - SkipList: API/STD/SkipList.md
      - DictHash: API/STD/DictHash.md

      - TreeVirtual: API/STD/TreeVirtual.md

      - BinTreeVirtual: API/STD/BinTreeVirtual.md
      - BinTreeArray: API/STD/BinTreeArray.md

      - Tree: API/STD/Tree.md
      - BinTree: API/STD/BinTree.md
      - BSTree: API/STD/BSTree.md
      - RBTree: API/STD/RBTree.md
      - BPTree: API/STD/BPTree.md
      - BTree: API/STD/BTree.md

      - WinnerTreeBinVirtual: API/STD/WinnerTreeBinVirtual.md
      - WinnerTreeVirtual: API/STD/WinnerTreeVirtual.md

      - WinnerTree: API/STD/WinnerTree.md
      - WinnerTreeBin: API/STD/WinnerTreeBin.md

      - MaxHeapVirtual: API/STD/MaxHeapVirtual.md
      - MinHeapVirtual: API/STD/MinHeapVirtual.md

      - MaxHeap: API/STD/MaxHeap.md
      - MinHeap: API/STD/MinHeap.md

      - PriorityQueueVirtual: API/STD/PriorityQueueVirtual.md
      - PriorityQueue: API/STD/PriorityQueue.md

      - GraphVirtual: API/STD/GraphVirtual.md
      - ADGraphVirtual: API/STD/ADGraphVirtual.md
      - ADWGraphVirtual: API/STD/ADWGraphVirtual.md

      - Graph: API/STD/Graph.md
      - LKGraph: API/STD/LKGraph.md
      - LKWGraph: API/STD/LKWGraph.md

  - 完整参考:
    - 参考: fullReference/hello.md